{
 "title": "Umami - Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "website",
    "query": {
     "query": "label_values(umami_metric_value,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fetch status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "umami_fetch_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Visitors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name) (rate(umami_website_visits[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active visitors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name) (rate(umami_website_active_visitors[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stats for $website", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "website" },
  {
   "title": "Visitors country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(value) (rate(umami_metric_value{name=~\"$website\", type=\"country\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visitors device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "sum by(value) (rate(umami_metric_value{name=~\"$website\", type=\"device\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visitors OS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum by(value) (rate(umami_metric_value{name=~\"$website\", type=\"os\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visitors browser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "sum by(value) (rate(umami_metric_value{name=~\"$website\", type=\"browser\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visitors bounce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "rate(umami_website_bounces{name=~\"$website\"}[2m])",
     "legendFormat": "Bounce"
    }
   ]
  }
 ]
}