apiVersion: v1
kind: Secret
metadata:
  name: umami-exporter-secret
type: Opaque
stringData:
  # Replace these values or use kubectl --from-literal to create the secret
  UMAMI_URL: "https://umami.example.com"
  UMAMI_USERNAME: "your-username"
  UMAMI_PASSWORD: "your-password"
  EXPORTER_PORT: "9465"
  UMAMI_REFRESH_INTERVAL: "1m"
  UMAMI_CONCURRENCY: "5"
  UMAMI_METRIC_LIMIT: "100"
  UMAMI_METRIC_TYPES: "url,referrer,browser,os,device,country,event"
  UMAMI_HTTP_TIMEOUT: "15s"